### ISSUE TITLE
[Help] DJI Manifold Wifi Problem

### ISSUE THREAD

**Issue by wkyoun** [lanyusea/djiros#21]
I have DJI Manifold, which is the customized version of Nvidia TK1

 The problem is that  I cannot added wifi to DJI Manifold using Intel 7260 mini PCIe.
 (Wifi is not available, ,but  ethernet is working correctly)

 However, I have sucessfully added Wifi to Nvidia TK1 after installing jetpack using Intel 7260 mini PCIe 

 based on following links: 

http://distrustsimplicity.net/articles/nvidia-jetson-tk1-wifi/

 Is there anyone who have successfully added wifi to DJI Manifold?
 (In the DJI Manual, it said that  the drivers for the intel 7260 HMW is preinstalled, but wireless port (wlan0) was not enable!)

 I tried to install OS image and kernel using Jetpack provided by Nvidia in the same way

 in which I I have sucessfully added Wifi to Nvidia TK1 , but it always failed.

 Moreover, I tried to install kernel as written in 

https://dl.djicdn.com/downloads/ ... anual__en__v1.0.pdf

 it always result in the failure while running the command "make" in kernel install!

 Last question: is it possbile for me to use DJI Manifold as it was shipped? 

 Thank you in Advanced.

**Comment by lanyusea** [comment]
please contact dev@dji.com
